import { useCallback, useEffect, useMemo, useState } from 'react';
import {
  Alert,
  Autocomplete,
  Box,
  Button,
  Card,
  CardContent,
  Chip,
  CircularProgress,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  Divider,
  IconButton,
  InputAdornment,
  MenuItem,
  Stack,
  TextField,
  Typography,
  useMediaQuery,
  useTheme,
} from '@mui/material';
import {
  Add as AddIcon,
  ArrowDownward as ArrowDownwardIcon,
  ArrowUpward as ArrowUpwardIcon,
  Delete as DeleteIcon,
  DragIndicator as DragIndicatorIcon,
  Edit as EditIcon,
  PictureAsPdf as PdfIcon,
  Refresh as RefreshIcon,
  Save as SaveIcon,
} from '@mui/icons-material';
import type {
  AuthState,
  CompanySettings,
  ComponentType,
  EstimateDocumentType,
  EstimatePdfTemplate,
  SavedEstimate,
  SavedEstimatePosition,
  SavedEstimateRoom,
} from '../types';
import {
  buildEstimatePdfItemsFromSavedPositions,
  buildSavedEstimatePositionPayloads,
  buildSavedEstimateRoomPayloads,
  createSavedEstimatePosition,
  normalizeSavedEstimatePositions,
  summarizeSavedEstimatePositions,
  toNumber as num,
} from '../features/estimates/calculationEngine';
import { cleanSearch, money } from '../utils';
import { restDelete, restInsert, restSelect, restUpdate } from '../supabaseRest';
import { supabase } from '../supabaseClient';

interface EstimatesPageProps {
  auth: AuthState;
  settings: CompanySettings;
}

interface EstimateDraft {
  title: string;
  clientName: string;
  clientPhone: string;
  clientEmail: string;
  objectAddress: string;
  clientComment: string;
  status: SavedEstimate['status'];
  documentType: EstimateDocumentType;
  pdfTemplate: EstimatePdfTemplate;
  pdfAccentColor: string;
  marginPercent: string;
  discountPercent: string;
  useCommonSection: boolean;
}

interface AddLocalPositionDraft {
  name: string;
  price: string;
  qty: string;
  unit: string;
  description: string;
  image: string;
  roomId: string;
  itemType?: 'tovar' | 'usluga' | 'uzel';
  item_id?: string;
  category?: string;
  subcategory?: string;
}

interface CatalogSearchOption {
  id: string;
  name: string;
  price: number;
  unit: string;
  category: string;
  subcategory: string;
  image?: string | null;
  description?: string | null;
  type: 'tovar' | 'usluga' | 'uzel';
}

const COMMON_ROOM = 'common';

function formatDate(value?: string | null) {
  if (!value) return '-';
  return new Intl.DateTimeFormat('ru-RU', {
    dateStyle: 'short',
    timeStyle: 'short',
  }).format(new Date(value));
}

function sourceSnapshot(position: SavedEstimatePosition): NonNullable<SavedEstimatePosition['source_snapshot']> {
  const snapshot = position.source_snapshot;
  return snapshot && typeof snapshot === 'object' ? snapshot : {};
}

function isAutoGenerated(position: SavedEstimatePosition) {
  const snapshot = sourceSnapshot(position);
  return snapshot.auto_generated === true || snapshot.source === 'smart-rule';
}

function isSchemaCacheError(error: unknown) {
  const message = error && typeof error === 'object' && 'message' in error
    ? String((error as { message?: string }).message || '')
    : String(error || '');

  return message.includes('schema cache')
    || message.includes('Could not find')
    || message.includes('does not exist');
}

function textValue(value: unknown) {
  return typeof value === 'string' ? value : '';
}

function estimateSettingsWithRules(estimate: SavedEstimate | undefined) {
  const snapshot = estimate?.settings_snapshot && typeof estimate.settings_snapshot === 'object'
    ? estimate.settings_snapshot
    : {};

  return {
    ...snapshot,
  };
}

function estimatePdfSettings(estimate: SavedEstimate | undefined, fallback: CompanySettings) {
  const snapshot = estimateSettingsWithRules(estimate);

  return {
    companyName: textValue(snapshot.companyName) || fallback.companyName,
    managerName: textValue(snapshot.managerName) || fallback.managerName,
    phone: textValue(snapshot.phone) || fallback.phone,
    email: textValue(snapshot.email) || fallback.email,
    pdfNote: textValue(snapshot.pdfNote) || fallback.pdfNote,
  };
}

function estimateDraftOf(estimate: SavedEstimate | undefined): EstimateDraft {
  return {
    title: estimate?.title || '',
    clientName: estimate?.client_name || '',
    clientPhone: estimate?.client_phone || '',
    clientEmail: estimate?.client_email || '',
    objectAddress: estimate?.object_address || '',
    clientComment: estimate?.client_comment || '',
    status: estimate?.status || 'draft',
    documentType: estimate?.document_type || 'preliminary',
    pdfTemplate: estimate?.pdf_template || 'wave',
    pdfAccentColor: estimate?.pdf_accent_color || '#D4146A',
    marginPercent: String(estimate?.margin_percent ?? 0),
    discountPercent: String(estimate?.discount_percent ?? 0),
    useCommonSection: estimate?.use_common_section !== false,
  };
}

function emptyAddDraft(): AddLocalPositionDraft {
  return {
    name: '',
    price: '',
    qty: '1',
    unit: 'шт.',
    description: '',
    image: '',
    roomId: COMMON_ROOM,
    category: 'Локальные',
    subcategory: '',
  };
}

function reindexPositions(positions: SavedEstimatePosition[]) {
  return positions.map((position, index) => ({
    ...position,
    position_index: index + 1,
  }));
}

export default function EstimatesPage({ auth, settings }: EstimatesPageProps) {
  const theme = useTheme();
  const isCompactLayout = useMediaQuery(theme.breakpoints.down('md'));

  const [estimates, setEstimates] = useState<SavedEstimate[]>([]);
  const [selectedId, setSelectedId] = useState('');
  const [rooms, setRooms] = useState<SavedEstimateRoom[]>([]);
  const [positions, setPositions] = useState<SavedEstimatePosition[]>([]);
  const [estimateDraft, setEstimateDraft] = useState<EstimateDraft>(() => estimateDraftOf(undefined));
  const [roomDrafts, setRoomDrafts] = useState<SavedEstimateRoom[]>([]);
  const [positionDrafts, setPositionDrafts] = useState<SavedEstimatePosition[]>([]);
  const [deletedRoomIds, setDeletedRoomIds] = useState<string[]>([]);
  const [deletedPositionIds, setDeletedPositionIds] = useState<string[]>([]);

  const [catalogSearch, setCatalogSearch] = useState('');
  const [catalogOptions, setCatalogOptions] = useState<CatalogSearchOption[]>([]);
  const [optionsLoading, setOptionsLoading] = useState(false);

  const [loading, setLoading] = useState(true);
  const [detailsLoading, setDetailsLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [addDraft, setAddDraft] = useState<AddLocalPositionDraft>(() => emptyAddDraft());
  const [editingPositionId, setEditingPositionId] = useState<string | null>(null);
  const [draggedPositionId, setDraggedPositionId] = useState<string | null>(null);
  const [dragOverPositionId, setDragOverPositionId] = useState<string | null>(null);

  const selectedEstimate = useMemo(
    () => estimates.find((estimate) => estimate.id === selectedId) || estimates[0],
    [estimates, selectedId]
  );

  const positionSummary = useMemo(
    () => summarizeSavedEstimatePositions(positionDrafts),
    [positionDrafts]
  );
  const currentTotal = positionSummary.total;

  const roomNameById = useMemo(
    () => new Map(roomDrafts.map((room) => [room.id, room.name || 'Комната'])),
    [roomDrafts]
  );

  const originalRoomIds = useMemo(() => new Set(rooms.map((room) => room.id)), [rooms]);
  const originalPositionIds = useMemo(() => new Set(positions.map((position) => position.id)), [positions]);

  function sectionNameOf(roomId?: string | null) {
    if (roomId && roomNameById.has(roomId)) return roomNameById.get(roomId)!;
    return estimateDraft.useCommonSection ? 'Общие работы' : 'Без комнаты';
  }

  useEffect(() => {
    if (catalogSearch.length < 2) {
      setCatalogOptions([]);
      return;
    }

    const timer = window.setTimeout(async () => {
      setOptionsLoading(true);

      try {
        const query = cleanSearch(catalogSearch);
        const [tovary, uslugi, uzly] = await Promise.all([
          supabase.from('tovary').select('id, name, price, unit, category, subcategory, image, description').ilike('name', `%${query}%`).limit(10),
          supabase.from('uslugi').select('id, name, price, unit, category, subcategory, image, description').ilike('name', `%${query}%`).limit(10),
          supabase.from('uzly').select('id, name, price, unit, category, subcategory, image, description').ilike('name', `%${query}%`).limit(10),
        ]);

        const combined: CatalogSearchOption[] = [
          ...(tovary.data || []).map((item) => ({ ...item, type: 'tovar' as const })),
          ...(uslugi.data || []).map((item) => ({ ...item, type: 'usluga' as const })),
          ...(uzly.data || []).map((item) => ({ ...item, type: 'uzel' as const })),
        ];

        setCatalogOptions(combined);
      } catch (searchError) {
        console.error('Search error:', searchError);
      } finally {
        setOptionsLoading(false);
      }
    }, 400);

    return () => window.clearTimeout(timer);
  }, [catalogSearch]);

  const loadEstimates = useCallback(async () => {
    setLoading(true);
    setError('');

    try {
      let rows: SavedEstimate[];

      try {
        rows = await restSelect<SavedEstimate>('smety', {
          select: 'id,user_id,title,client_name,client_phone,client_email,object_address,client_comment,margin_percent,discount_percent,subtotal,total,status,document_type,pdf_template,pdf_accent_color,use_common_section,room_count,items_count,components_count,settings_snapshot,created_at,updated_at',
          order: 'created_at.desc',
          limit: 50,
        });
      } catch (loadError) {
        if (!isSchemaCacheError(loadError)) throw loadError;

        rows = await restSelect<SavedEstimate>('smety', {
          select: 'id,user_id,client_name,client_phone,margin_percent,discount_percent,subtotal,total,status,created_at,updated_at',
          order: 'created_at.desc',
          limit: 50,
        });
      }

      setEstimates(rows);
      if (!selectedId && rows[0]) {
        setSelectedId(rows[0].id);
      }
    } catch (loadError) {
      const message = loadError instanceof Error ? loadError.message : String(loadError);
      setError(`${message} Проверь миграции смет.`);
      setEstimates([]);
    }

    setLoading(false);
  }, [selectedId]);

  useEffect(() => {
    if (auth.userId) loadEstimates();
  }, [auth.userId, loadEstimates]);

  useEffect(() => {
    setEstimateDraft(estimateDraftOf(selectedEstimate));
  }, [selectedEstimate]);

  useEffect(() => {
    if (!selectedEstimate?.id) {
      setRooms([]);
      setPositions([]);
      setRoomDrafts([]);
      setPositionDrafts([]);
      return;
    }

    let cancelled = false;

    async function loadDetails() {
      setDetailsLoading(true);
      setError('');
      setNotice('');

      try {
        const roomsPromise = restSelect<SavedEstimateRoom>('smeta_komnaty', {
          select: 'id,smeta_id,position_index,name,area,perimeter,corners,light_points,pipes,curtain_tracks,niches,comment',
          filters: { smeta_id: selectedEstimate.id },
          order: 'position_index.asc',
        }).catch((loadError) => {
          if (isSchemaCacheError(loadError)) return [] as SavedEstimateRoom[];
          throw loadError;
        });

        const positionsPromise = restSelect<SavedEstimatePosition>('smeta_pozicii', {
          select: 'id,smeta_id,position_index,room_id,item_type,item_id,item_name,qty,unit,price,total,category,subcategory,base_price,item_snapshot,components_snapshot,source_snapshot',
          filters: { smeta_id: selectedEstimate.id },
          order: 'position_index.asc',
        }).catch((loadError) => {
          if (!isSchemaCacheError(loadError)) throw loadError;

          return restSelect<SavedEstimatePosition>('smeta_pozicii', {
            select: 'id,smeta_id,item_type,item_id,item_name,qty,unit,price,total,created_at',
            filters: { smeta_id: selectedEstimate.id },
            order: 'created_at.asc',
          });
        });

        const [roomRows, positionRows] = await Promise.all([roomsPromise, positionsPromise]);
        if (cancelled) return;

        setRooms(roomRows);
        setPositions(positionRows);
        setRoomDrafts(roomRows);
        setPositionDrafts(positionRows);
        setDeletedRoomIds([]);
        setDeletedPositionIds([]);
      } catch (loadError) {
        if (cancelled) return;
        const message = loadError instanceof Error ? loadError.message : String(loadError);
        setError(`${message} Проверь миграции смет.`);
        setRooms([]);
        setPositions([]);
        setRoomDrafts([]);
        setPositionDrafts([]);
      }

      setDetailsLoading(false);
    }

    loadDetails();
    return () => { cancelled = true; };
  }, [selectedEstimate]);

  function updatePosition(positionId: string, patch: Partial<SavedEstimatePosition>) {
    setPositionDrafts((prev) => prev.map((position) => {
      if (position.id !== positionId) return position;
      const next = { ...position, ...patch };
      const qty = num(next.qty);
      const price = num(next.price);
      return { ...next, qty, price, total: qty * price };
    }));
  }

  function updatePositionSource(positionId: string, patch: NonNullable<SavedEstimatePosition['source_snapshot']>) {
    setPositionDrafts((prev) => prev.map((position) => {
      if (position.id !== positionId) return position;
      return {
        ...position,
        source_snapshot: {
          ...sourceSnapshot(position),
          ...patch,
        },
      };
    }));
  }

  function removePosition(positionId: string) {
    if (originalPositionIds.has(positionId)) {
      setDeletedPositionIds((prev) => [...new Set([...prev, positionId])]);
    }

    setPositionDrafts((prev) => reindexPositions(prev.filter((position) => position.id !== positionId)));
  }

  function movePosition(fromId: string, toId: string) {
    if (fromId === toId) return;

    setPositionDrafts((prev) => {
      const fromIndex = prev.findIndex((position) => position.id === fromId);
      const toIndex = prev.findIndex((position) => position.id === toId);

      if (fromIndex === -1 || toIndex === -1) return prev;

      const next = [...prev];
      const [moved] = next.splice(fromIndex, 1);
      next.splice(toIndex, 0, moved);
      return reindexPositions(next);
    });
  }

  function movePositionByStep(positionId: string, direction: -1 | 1) {
    setPositionDrafts((prev) => {
      const index = prev.findIndex((position) => position.id === positionId);
      const targetIndex = index + direction;

      if (index === -1 || targetIndex < 0 || targetIndex >= prev.length) {
        return prev;
      }

      const next = [...prev];
      const [moved] = next.splice(index, 1);
      next.splice(targetIndex, 0, moved);
      return reindexPositions(next);
    });
  }

  async function handleAddPosition() {
    if (!selectedEstimate) return;

    const name = addDraft.name.trim();
    if (!name) {
      setError('Введите название позиции');
      return;
    }

    let componentsSnapshot: NonNullable<SavedEstimatePosition['components_snapshot']> = [];

    if (addDraft.itemType === 'uzel' && addDraft.item_id) {
      const nodeComponents = await restSelect<{
        item_type: ComponentType;
        item_id: string;
        item_name: string;
        qty: number;
        unit: string;
        price: number;
        total: number;
        category?: string | null;
        subcategory?: string | null;
      }>('komplektaciya_uzlov', {
        select: 'item_type,item_id,item_name,qty,unit,price,total,category,subcategory',
        filters: { uzel_id: addDraft.item_id },
        order: 'position_index.asc',
      });

      // Для узла сохраняем состав прямо в смету, чтобы редактор и PDF не теряли
      // материалы и работы, даже если каталог позже изменится.
      componentsSnapshot = nodeComponents.map((component) => ({
        item_type: component.item_type,
        item_id: component.item_id,
        item_name: component.item_name,
        qty: num(component.qty),
        unit: component.unit || 'шт.',
        price: num(component.price),
        total: num(component.total) || num(component.price) * num(component.qty),
        category: component.category || null,
        subcategory: component.subcategory || null,
      }));
    }

    const position = createSavedEstimatePosition({
      estimateId: selectedEstimate.id,
      positionIndex: positionDrafts.length + 1,
      roomId: addDraft.roomId === COMMON_ROOM ? null : addDraft.roomId,
      itemType: addDraft.itemType || 'tovar',
      itemId: addDraft.item_id,
      name,
      qty: addDraft.qty,
      unit: addDraft.unit,
      price: addDraft.price,
      category: addDraft.category,
      subcategory: addDraft.subcategory,
      image: addDraft.image.trim() || null,
      description: addDraft.description.trim() || null,
      source: addDraft.item_id ? 'catalog' : 'local',
      componentsSnapshot,
    });

    try {
      await restInsert('smeta_pozicii', buildSavedEstimatePositionPayloads(selectedEstimate.id, [position])[0], { returning: 'minimal' });

      const nextPositions = reindexPositions([...positionDrafts, position]);
      const nextSummary = summarizeSavedEstimatePositions(nextPositions);

      await restUpdate('smety', {
        subtotal: nextSummary.subtotal,
        total: nextSummary.total,
        room_count: roomDrafts.length,
        items_count: nextSummary.itemsCount,
        components_count: nextSummary.componentsCount,
        updated_at: new Date().toISOString(),
      }, {
        filters: { id: selectedEstimate.id },
        returning: 'minimal',
      });

      setPositions((prev) => [...prev, position]);
      setPositionDrafts(nextPositions);
      setAddDraft(emptyAddDraft());
      setNotice('Позиция успешно добавлена.');
    } catch (addError) {
      setError(addError instanceof Error ? addError.message : String(addError));
    }
  }

  async function saveEstimateEditor() {
    if (!selectedEstimate) return;

    setSaving(true);
    setError('');
    setNotice('');

    const pdfSettings = estimatePdfSettings(selectedEstimate, settings);
    const validRoomIds = new Set(roomDrafts.map((room) => room.id));
    const normalizedPositions = normalizeSavedEstimatePositions(positionDrafts, validRoomIds);
    const normalizedSummary = summarizeSavedEstimatePositions(normalizedPositions);

    try {
      await restUpdate('smety', {
        title: estimateDraft.title.trim() || 'Без названия',
        client_name: estimateDraft.clientName.trim() || null,
        client_phone: estimateDraft.clientPhone.trim() || null,
        client_email: estimateDraft.clientEmail.trim() || null,
        object_address: estimateDraft.objectAddress.trim() || null,
        client_comment: estimateDraft.clientComment.trim() || null,
        status: estimateDraft.status,
        document_type: estimateDraft.documentType,
        pdf_template: estimateDraft.pdfTemplate,
        pdf_accent_color: estimateDraft.pdfAccentColor,
        use_common_section: estimateDraft.useCommonSection,
        margin_percent: num(estimateDraft.marginPercent),
        discount_percent: num(estimateDraft.discountPercent),
        subtotal: normalizedSummary.subtotal,
        total: normalizedSummary.total,
        room_count: roomDrafts.length,
        items_count: normalizedSummary.itemsCount,
        components_count: normalizedSummary.componentsCount,
        settings_snapshot: {
          ...estimateSettingsWithRules(selectedEstimate),
          companyName: pdfSettings.companyName,
          managerName: pdfSettings.managerName,
          phone: pdfSettings.phone,
          email: pdfSettings.email,
          pdfNote: pdfSettings.pdfNote,
          marginPercent: num(estimateDraft.marginPercent),
          discountPercent: num(estimateDraft.discountPercent),
        },
        updated_at: new Date().toISOString(),
      }, {
        filters: { id: selectedEstimate.id },
        returning: 'minimal',
      });

      await Promise.all(deletedPositionIds.map((id) => restDelete('smeta_pozicii', {
        filters: { id },
        returning: 'minimal',
      })));

      await Promise.all(deletedRoomIds.map((id) => restDelete('smeta_komnaty', {
        filters: { id },
        returning: 'minimal',
      })));

      const roomPayloads = buildSavedEstimateRoomPayloads(selectedEstimate.id, roomDrafts);
      const newRooms = roomPayloads.filter((room) => !originalRoomIds.has(room.id));
      const existingRooms = roomPayloads.filter((room) => originalRoomIds.has(room.id));

      if (newRooms.length > 0) {
        await restInsert('smeta_komnaty', newRooms, { returning: 'minimal' });
      }

      await Promise.all(existingRooms.map((room) => restUpdate('smeta_komnaty', room, {
        filters: { id: room.id },
        returning: 'minimal',
      })));

      const positionPayloads = buildSavedEstimatePositionPayloads(selectedEstimate.id, normalizedPositions);
      const newPositions = positionPayloads.filter((position) => !originalPositionIds.has(position.id));
      const existingPositions = positionPayloads.filter((position) => originalPositionIds.has(position.id));

      if (newPositions.length > 0) {
        await restInsert('smeta_pozicii', newPositions, { returning: 'minimal' });
      }

      await Promise.all(existingPositions.map((position) => restUpdate('smeta_pozicii', position, {
        filters: { id: position.id },
        returning: 'minimal',
      })));

      const savedRooms: SavedEstimateRoom[] = roomPayloads.map((room) => ({ ...room }));
      const savedPositions: SavedEstimatePosition[] = positionPayloads.map((position) => ({ ...position }));

      setRooms(savedRooms);
      setPositions(savedPositions);
      setRoomDrafts(savedRooms);
      setPositionDrafts(savedPositions);
      setDeletedRoomIds([]);
      setDeletedPositionIds([]);
      setNotice('Изменения сохранены.');
      await loadEstimates();
      setSelectedId(selectedEstimate.id);
    } catch (saveError) {
      setError(saveError instanceof Error ? saveError.message : String(saveError));
    } finally {
      setSaving(false);
    }
  }

  async function handlePdfExport() {
    if (!selectedEstimate) return;

    const pdfSettings = estimatePdfSettings(selectedEstimate, settings);
    const { generatePdf } = await import('../PdfExport');

    generatePdf(buildEstimatePdfItemsFromSavedPositions(positionDrafts, sectionNameOf), {
      title: estimateDraft.title,
      documentType: estimateDraft.documentType,
      template: estimateDraft.pdfTemplate,
      accentColor: estimateDraft.pdfAccentColor,
      clientName: estimateDraft.clientName,
      clientPhone: estimateDraft.clientPhone,
      clientEmail: estimateDraft.clientEmail,
      objectAddress: estimateDraft.objectAddress,
      clientComment: estimateDraft.clientComment,
      total: currentTotal,
      companyName: pdfSettings.companyName,
      managerName: pdfSettings.managerName,
      phone: pdfSettings.phone,
      email: pdfSettings.email,
      note: pdfSettings.pdfNote,
    });
  }

  const editingPosition = editingPositionId
    ? positionDrafts.find((position) => position.id === editingPositionId) || null
    : null;

  return (
    <Box sx={{ p: { xs: 1.5, sm: 2, lg: 3 }, maxWidth: 1500, mx: 'auto' }}>
      <Stack direction={{ xs: 'column', md: 'row' }} sx={{ alignItems: { md: 'center' }, justifyContent: 'space-between', gap: 2, mb: 3 }}>
        <Box>
          <Typography variant="h4">Сметы</Typography>
          <Typography color="text.secondary" sx={{ mt: 0.5 }}>
            Менеджерский редактор сохранённых смет.
          </Typography>
        </Box>
        <Button variant="outlined" startIcon={<RefreshIcon />} onClick={loadEstimates} disabled={loading}>
          Обновить
        </Button>
      </Stack>

      {error && <Alert severity="error" sx={{ mb: 2 }} onClose={() => setError('')}>{error}</Alert>}
      {notice && <Alert severity="success" sx={{ mb: 2 }} onClose={() => setNotice('')}>{notice}</Alert>}

      {loading ? (
        <Stack direction="row" spacing={2} sx={{ alignItems: 'center' }}>
          <CircularProgress size={22} />
          <Typography color="text.secondary">Загружаю сметы...</Typography>
        </Stack>
      ) : estimates.length === 0 ? (
        <Card>
          <CardContent>
            <Alert severity="info">Пока нет сохранённых смет.</Alert>
          </CardContent>
        </Card>
      ) : (
        <Stack direction={{ xs: 'column', lg: 'row' }} spacing={3} sx={{ alignItems: 'flex-start' }}>
          <Stack spacing={2} sx={{ width: { xs: '100%', lg: 360 }, flexShrink: 0 }}>
            {estimates.map((estimate) => (
              <Card
                key={estimate.id}
                onClick={() => setSelectedId(estimate.id)}
                sx={{
                  cursor: 'pointer',
                  borderRadius: 3,
                  boxShadow: '0 4px 15px rgba(0,0,0,0.03)',
                  borderColor: selectedEstimate?.id === estimate.id ? 'primary.main' : 'divider',
                  borderWidth: selectedEstimate?.id === estimate.id ? 2 : 1,
                }}
              >
                <CardContent>
                  <Stack spacing={1}>
                    <Typography variant="h6">{estimate.title || estimate.client_name || 'Без названия'}</Typography>
                    <Typography color="text.secondary">{estimate.client_name || 'Клиент не указан'}</Typography>
                    <Typography variant="body2" color="text.secondary">{formatDate(estimate.created_at)}</Typography>
                    <Stack direction="row" sx={{ justifyContent: 'space-between' }}>
                      <Typography variant="body2" color="text.secondary">
                        {estimate.items_count || 0} поз.
                      </Typography>
                      <Typography sx={{ fontWeight: 700 }}>{money(num(estimate.total))}</Typography>
                    </Stack>
                  </Stack>
                </CardContent>
              </Card>
            ))}
          </Stack>

          <Box sx={{ flexGrow: 1, width: '100%' }}>
            {selectedEstimate && (
              <Card sx={{ boxShadow: '0 8px 30px rgba(0,0,0,0.04)', borderRadius: 3 }}>
                <CardContent>
                  <Stack direction={{ xs: 'column', md: 'row' }} sx={{ justifyContent: 'space-between', gap: 2, mb: 2 }}>
                    <Box>
                      <Typography variant="h5">{estimateDraft.title || estimateDraft.clientName || 'Без названия'}</Typography>
                      <Typography variant="h4" color="primary.main">{money(currentTotal)}</Typography>
                    </Box>
                    <Stack direction={{ xs: 'column', sm: 'row' }} spacing={1} sx={{ width: { xs: '100%', md: 'auto' } }}>
                      <Button variant="outlined" startIcon={<PdfIcon />} disabled={positionDrafts.length === 0} onClick={handlePdfExport} fullWidth={isCompactLayout}>
                        PDF
                      </Button>
                      <Button variant="contained" startIcon={<SaveIcon />} disabled={saving || detailsLoading} onClick={saveEstimateEditor} fullWidth={isCompactLayout}>
                        {saving ? 'Сохраняю...' : 'Сохранить изменения'}
                      </Button>
                    </Stack>
                  </Stack>

                  <Divider sx={{ my: 2 }} />

                  {detailsLoading ? (
                    <Stack direction="row" spacing={2} sx={{ alignItems: 'center' }}>
                      <CircularProgress size={22} />
                      <Typography color="text.secondary">Загружаю детали...</Typography>
                    </Stack>
                  ) : (
                    <Stack spacing={3}>
                      <Box sx={{ p: { xs: 1.5, md: 2 }, borderRadius: 3, bgcolor: 'grey.50' }}>
                        <Typography variant="h6" sx={{ mb: 2 }}>Реквизиты сметы</Typography>
                        <Stack spacing={2}>
                          <Stack direction={{ xs: 'column', md: 'row' }} spacing={2}>
                            <TextField
                              label="Название сметы"
                              value={estimateDraft.title}
                              onChange={(event) => setEstimateDraft((prev) => ({ ...prev, title: event.target.value }))}
                              fullWidth
                            />
                            <TextField
                              select
                              label="Статус"
                              value={estimateDraft.status}
                              onChange={(event) => setEstimateDraft((prev) => ({ ...prev, status: event.target.value as SavedEstimate['status'] }))}
                              sx={{ minWidth: { md: 180 } }}
                            >
                              <MenuItem value="draft">Черновик</MenuItem>
                              <MenuItem value="sent">Отправлено</MenuItem>
                              <MenuItem value="accepted">Принято</MenuItem>
                              <MenuItem value="archived">Архив</MenuItem>
                            </TextField>
                            <TextField
                              select
                              label="Документ"
                              value={estimateDraft.documentType}
                              onChange={(event) => setEstimateDraft((prev) => ({ ...prev, documentType: event.target.value as EstimateDocumentType }))}
                              sx={{ minWidth: { md: 180 } }}
                            >
                              <MenuItem value="preliminary">Предварительный</MenuItem>
                              <MenuItem value="final">Финальный</MenuItem>
                            </TextField>
                          </Stack>

                          <Stack direction={{ xs: 'column', md: 'row' }} spacing={2}>
                            <TextField
                              label="Клиент"
                              value={estimateDraft.clientName}
                              onChange={(event) => setEstimateDraft((prev) => ({ ...prev, clientName: event.target.value }))}
                              fullWidth
                            />
                            <TextField
                              label="Телефон"
                              value={estimateDraft.clientPhone}
                              onChange={(event) => setEstimateDraft((prev) => ({ ...prev, clientPhone: event.target.value }))}
                              fullWidth
                            />
                            <TextField
                              label="Email"
                              value={estimateDraft.clientEmail}
                              onChange={(event) => setEstimateDraft((prev) => ({ ...prev, clientEmail: event.target.value }))}
                              fullWidth
                            />
                          </Stack>

                          <Stack direction={{ xs: 'column', md: 'row' }} spacing={2}>
                            <TextField
                              label="Адрес объекта"
                              value={estimateDraft.objectAddress}
                              onChange={(event) => setEstimateDraft((prev) => ({ ...prev, objectAddress: event.target.value }))}
                              fullWidth
                            />
                            <TextField
                              select
                              label="Шаблон PDF"
                              value={estimateDraft.pdfTemplate}
                              onChange={(event) => setEstimateDraft((prev) => ({ ...prev, pdfTemplate: event.target.value as EstimatePdfTemplate }))}
                              sx={{ minWidth: { md: 180 } }}
                            >
                              <MenuItem value="classic">Classic</MenuItem>
                              <MenuItem value="wave">Wave</MenuItem>
                              <MenuItem value="stripe">Stripe</MenuItem>
                              <MenuItem value="dark">Dark</MenuItem>
                            </TextField>
                            <TextField
                              label="Акцент PDF"
                              value={estimateDraft.pdfAccentColor}
                              onChange={(event) => setEstimateDraft((prev) => ({ ...prev, pdfAccentColor: event.target.value }))}
                              sx={{ minWidth: { md: 180 } }}
                            />
                          </Stack>

                          <Stack direction={{ xs: 'column', md: 'row' }} spacing={2}>
                            <TextField
                              label="Маржа, %"
                              type="number"
                              value={estimateDraft.marginPercent}
                              onChange={(event) => setEstimateDraft((prev) => ({ ...prev, marginPercent: event.target.value }))}
                              sx={{ width: { md: 160 } }}
                            />
                            <TextField
                              label="Скидка, %"
                              type="number"
                              value={estimateDraft.discountPercent}
                              onChange={(event) => setEstimateDraft((prev) => ({ ...prev, discountPercent: event.target.value }))}
                              sx={{ width: { md: 160 } }}
                            />
                            <TextField
                              select
                              label="Раздел без комнаты"
                              value={estimateDraft.useCommonSection ? 'common' : 'none'}
                              onChange={(event) => setEstimateDraft((prev) => ({ ...prev, useCommonSection: event.target.value === 'common' }))}
                              sx={{ minWidth: { md: 220 } }}
                            >
                              <MenuItem value="common">Общие работы</MenuItem>
                              <MenuItem value="none">Без комнаты</MenuItem>
                            </TextField>
                          </Stack>

                          <TextField
                            label="Комментарий"
                            value={estimateDraft.clientComment}
                            onChange={(event) => setEstimateDraft((prev) => ({ ...prev, clientComment: event.target.value }))}
                            multiline
                            minRows={2}
                            fullWidth
                          />
                        </Stack>
                      </Box>

                      <Box>
                        <Stack direction={{ xs: 'column', sm: 'row' }} sx={{ justifyContent: 'space-between', alignItems: { sm: 'center' }, gap: 1, mb: 2 }}>
                          <Box>
                            <Typography variant="h6">Комнаты</Typography>
                            <Typography variant="body2" color="text.secondary">
                              Эти метрики уже сохранены в смете и помогают менеджеру быстро понимать, откуда взялся расчёт.
                            </Typography>
                          </Box>
                          <Chip size="small" variant="outlined" label={`${roomDrafts.length} комн.`} />
                        </Stack>

                        <Stack spacing={1.25}>
                          {roomDrafts.map((room) => (
                            <Box key={room.id} sx={{ p: 1.5, borderRadius: 2, border: '1px solid', borderColor: 'divider' }}>
                              <Stack direction={{ xs: 'column', md: 'row' }} sx={{ justifyContent: 'space-between', gap: 1 }}>
                                <Box>
                                  <Typography sx={{ fontWeight: 700 }}>{room.name}</Typography>
                                  <Typography variant="body2" color="text.secondary">{room.comment || 'Без заметки'}</Typography>
                                </Box>
                                <Stack direction="row" spacing={1} sx={{ flexWrap: 'wrap', gap: 1 }}>
                                  <Chip size="small" label={`Площадь: ${num(room.area)} м²`} />
                                  <Chip size="small" label={`Периметр: ${num(room.perimeter)} м`} />
                                  <Chip size="small" label={`Свет: ${num(room.light_points)}`} />
                                  <Chip size="small" label={`Трубы: ${num(room.pipes)}`} />
                                </Stack>
                              </Stack>
                            </Box>
                          ))}
                        </Stack>
                      </Box>

                      <Box>
                        <Stack direction={{ xs: 'column', sm: 'row' }} sx={{ justifyContent: 'space-between', alignItems: { sm: 'center' }, gap: 1, mb: 2 }}>
                          <Box>
                            <Typography variant="h6">Позиции сметы</Typography>
                            <Typography variant="body2" color="text.secondary">
                              Цена и количество редактируются прямо в списке. На компьютере позиции можно перетаскивать мышкой, на планшетах и телефонах есть кнопки вверх и вниз.
                            </Typography>
                          </Box>
                          {positionDrafts.length > 1 && (
                            <Chip
                              size="small"
                              variant="outlined"
                              label={isCompactLayout ? 'Порядок: кнопками' : 'Порядок: drag & drop'}
                            />
                          )}
                        </Stack>

                        <Box sx={{ mb: 4, p: { xs: 1.5, md: 2.5 }, bgcolor: 'primary.50', borderRadius: 3, border: '1px solid', borderColor: 'primary.100' }}>
                          <Typography variant="subtitle1" sx={{ fontWeight: 700, mb: 2, color: 'primary.dark' }}>Добавить позицию</Typography>
                          <Stack spacing={2}>
                            <Stack direction={{ xs: 'column', md: 'row' }} spacing={2}>
                              <Autocomplete
                                fullWidth
                                options={catalogOptions}
                                loading={optionsLoading}
                                getOptionLabel={(option) => typeof option === 'string' ? option : option.name}
                                onInputChange={(_, value, reason) => {
                                  setCatalogSearch(value);

                                  if (reason === 'clear') {
                                    setAddDraft(emptyAddDraft());
                                    return;
                                  }

                                  if (reason === 'input') {
                                    setAddDraft((prev) => ({
                                      ...prev,
                                      name: value,
                                      image: '',
                                      description: '',
                                      itemType: undefined,
                                      item_id: undefined,
                                    }));
                                  }
                                }}
                                onChange={(_, newValue) => {
                                  if (newValue && typeof newValue !== 'string') {
                                    setAddDraft((prev) => ({
                                      ...prev,
                                      name: newValue.name,
                                      price: String(newValue.price || ''),
                                      unit: newValue.unit || 'шт.',
                                      image: newValue.image || '',
                                      description: newValue.description || '',
                                      itemType: newValue.type,
                                      item_id: newValue.id,
                                      category: newValue.category,
                                      subcategory: newValue.subcategory,
                                    }));
                                    return;
                                  }

                                  if (typeof newValue === 'string') {
                                    setAddDraft((prev) => ({
                                      ...prev,
                                      name: newValue,
                                      image: '',
                                      description: '',
                                      itemType: undefined,
                                      item_id: undefined,
                                    }));
                                  }
                                }}
                                freeSolo
                                renderInput={(params) => (
                                  <TextField
                                    {...params}
                                    label="Поиск в каталоге или своё название"
                                    placeholder="Начните вводить..."
                                    slotProps={{
                                      input: {
                                        ...params.slotProps?.input,
                                        endAdornment: (
                                          <>
                                            {optionsLoading ? <CircularProgress color="inherit" size={20} /> : null}
                                            {params.slotProps?.input?.endAdornment}
                                          </>
                                        ),
                                      },
                                    }}
                                  />
                                )}
                              />

                              <TextField
                                select
                                label="Раздел"
                                value={addDraft.roomId}
                                onChange={(event) => setAddDraft((prev) => ({ ...prev, roomId: event.target.value }))}
                                sx={{ minWidth: 220 }}
                              >
                                {estimateDraft.useCommonSection && <MenuItem value={COMMON_ROOM}>Общие работы</MenuItem>}
                                {roomDrafts.map((room) => (
                                  <MenuItem key={room.id} value={room.id}>{room.name}</MenuItem>
                                ))}
                              </TextField>
                            </Stack>

                            <Stack direction={{ xs: 'column', md: 'row' }} spacing={2}>
                              <TextField
                                label="Кол-во"
                                type="number"
                                value={addDraft.qty}
                                onChange={(event) => setAddDraft((prev) => ({ ...prev, qty: event.target.value }))}
                                sx={{ width: { md: 120 } }}
                              />
                              <TextField
                                label="Ед. изм."
                                value={addDraft.unit}
                                onChange={(event) => setAddDraft((prev) => ({ ...prev, unit: event.target.value }))}
                                sx={{ width: { md: 100 } }}
                              />
                              <TextField
                                label="Цена"
                                type="number"
                                value={addDraft.price}
                                onChange={(event) => setAddDraft((prev) => ({ ...prev, price: event.target.value }))}
                                sx={{ width: { md: 150 } }}
                                slotProps={{ input: { endAdornment: <InputAdornment position="end">₽</InputAdornment> } }}
                              />
                              <TextField
                                label="Категория"
                                value={addDraft.category}
                                onChange={(event) => setAddDraft((prev) => ({ ...prev, category: event.target.value }))}
                                fullWidth
                              />
                              <TextField
                                label="Подкатегория"
                                value={addDraft.subcategory}
                                onChange={(event) => setAddDraft((prev) => ({ ...prev, subcategory: event.target.value }))}
                                fullWidth
                              />
                            </Stack>

                            <Stack direction={{ xs: 'column', md: 'row' }} spacing={2}>
                              <TextField
                                label="Описание"
                                value={addDraft.description}
                                onChange={(event) => setAddDraft((prev) => ({ ...prev, description: event.target.value }))}
                                multiline
                                maxRows={3}
                                fullWidth
                              />
                            </Stack>

                            <Stack direction={{ xs: 'column', md: 'row' }} spacing={2} sx={{ alignItems: 'center' }}>
                              <TextField
                                label="URL картинки"
                                value={addDraft.image}
                                onChange={(event) => setAddDraft((prev) => ({ ...prev, image: event.target.value }))}
                                fullWidth
                              />
                              <Button
                                variant="contained"
                                size="large"
                                onClick={handleAddPosition}
                                startIcon={<AddIcon />}
                                sx={{ height: 56, px: 4, borderRadius: 2, flexShrink: 0, width: { xs: '100%', md: 'auto' } }}
                              >
                                Добавить
                              </Button>
                            </Stack>
                          </Stack>
                        </Box>

                        <Stack spacing={1.5}>
                          {positionDrafts.map((position, index) => {
                            const source = sourceSnapshot(position);
                            const autoGenerated = isAutoGenerated(position);

                            return (
                              <Box
                                key={position.id}
                                draggable={!isCompactLayout}
                                onDragStart={() => {
                                  if (isCompactLayout) return;
                                  setDraggedPositionId(position.id);
                                }}
                                onDragOver={(event) => {
                                  if (isCompactLayout) return;
                                  event.preventDefault();
                                  setDragOverPositionId(position.id);
                                }}
                                onDrop={(event) => {
                                  if (isCompactLayout) return;
                                  event.preventDefault();

                                  if (draggedPositionId) {
                                    movePosition(draggedPositionId, position.id);
                                  }

                                  setDraggedPositionId(null);
                                  setDragOverPositionId(null);
                                }}
                                onDragEnd={() => {
                                  setDraggedPositionId(null);
                                  setDragOverPositionId(null);
                                }}
                                sx={{
                                  p: { xs: 1.25, sm: 1.5 },
                                  border: '1px solid',
                                  borderColor: dragOverPositionId === position.id
                                    ? 'primary.main'
                                    : autoGenerated
                                      ? 'primary.light'
                                      : 'divider',
                                  borderRadius: 2,
                                  bgcolor: autoGenerated ? 'primary.50' : 'background.paper',
                                  opacity: draggedPositionId === position.id ? 0.7 : 1,
                                }}
                              >
                                <Stack direction={{ xs: 'column', xl: 'row' }} spacing={2} sx={{ alignItems: { xl: 'center' } }}>
                                  <Stack direction="row" spacing={1.25} sx={{ flexGrow: 1, minWidth: 0, alignItems: 'flex-start' }}>
                                    <Box sx={{ display: { xs: 'none', md: 'flex' }, color: 'text.secondary', pt: 0.75, cursor: isCompactLayout ? 'default' : 'grab' }}>
                                      <DragIndicatorIcon fontSize="small" />
                                    </Box>

                                    <Box sx={{ flexGrow: 1, minWidth: 0 }}>
                                      <Stack direction="row" spacing={1} sx={{ flexWrap: 'wrap', gap: 1, mb: 1 }}>
                                        <Chip size="small" variant="outlined" label={`Раздел: ${sectionNameOf(position.room_id)}`} />
                                        {autoGenerated && <Chip size="small" color="primary" label="Автоправило" />}
                                        {source.rule_label && <Chip size="small" variant="outlined" label={source.rule_label} />}
                                        <Chip
                                          size="small"
                                          variant="outlined"
                                          label={
                                            position.category
                                              ? `${position.category}${position.subcategory ? ` / ${position.subcategory}` : ''}`
                                              : 'Без категории'
                                          }
                                        />
                                      </Stack>

                                      <TextField
                                        size="small"
                                        label="Название"
                                        value={position.item_name}
                                        onChange={(event) => updatePosition(position.id, { item_name: event.target.value })}
                                        fullWidth
                                      />
                                    </Box>
                                  </Stack>

                                  <Stack direction={{ xs: 'column', sm: 'row' }} spacing={1} sx={{ alignItems: { sm: 'flex-end' }, width: { xs: '100%', xl: 'auto' } }}>
                                    <TextField
                                      size="small"
                                      label="Кол-во"
                                      type="number"
                                      value={position.qty}
                                      onChange={(event) => updatePosition(position.id, { qty: num(event.target.value) })}
                                      sx={{ width: { sm: 110 } }}
                                    />
                                    <TextField
                                      size="small"
                                      label="Ед."
                                      value={position.unit || ''}
                                      onChange={(event) => updatePosition(position.id, { unit: event.target.value })}
                                      sx={{ width: { sm: 90 } }}
                                    />
                                    <TextField
                                      size="small"
                                      label="Цена"
                                      type="number"
                                      value={position.price}
                                      onChange={(event) => updatePosition(position.id, { price: num(event.target.value) })}
                                      sx={{ width: { sm: 150 } }}
                                      slotProps={{ input: { endAdornment: <InputAdornment position="end">₽</InputAdornment> } }}
                                    />

                                    <Box sx={{ minWidth: { sm: 130 }, px: 1, py: 0.75, borderRadius: 1.5, bgcolor: 'grey.50', textAlign: { sm: 'right' } }}>
                                      <Typography variant="caption" color="text.secondary">Итого</Typography>
                                      <Typography sx={{ fontWeight: 700, fontSize: '1rem' }}>{money(num(position.total))}</Typography>
                                    </Box>

                                    <Stack direction="row" spacing={0.5} sx={{ justifyContent: 'flex-end', flexWrap: 'wrap' }}>
                                      {isCompactLayout && (
                                        <>
                                          <IconButton color="inherit" onClick={() => movePositionByStep(position.id, -1)} disabled={index === 0}>
                                            <ArrowUpwardIcon />
                                          </IconButton>
                                          <IconButton color="inherit" onClick={() => movePositionByStep(position.id, 1)} disabled={index === positionDrafts.length - 1}>
                                            <ArrowDownwardIcon />
                                          </IconButton>
                                        </>
                                      )}

                                      <IconButton color="primary" onClick={() => setEditingPositionId(position.id)}>
                                        <EditIcon />
                                      </IconButton>
                                      <IconButton color="error" onClick={() => removePosition(position.id)}>
                                        <DeleteIcon />
                                      </IconButton>
                                    </Stack>
                                  </Stack>
                                </Stack>
                              </Box>
                            );
                          })}

                          {positionDrafts.length === 0 && <Alert severity="info">В смете пока нет позиций.</Alert>}
                        </Stack>
                      </Box>
                    </Stack>
                  )}
                </CardContent>
              </Card>
            )}
          </Box>
        </Stack>
      )}

      {editingPosition && (
        <Dialog open onClose={() => setEditingPositionId(null)} maxWidth="md" fullWidth fullScreen={isCompactLayout}>
          <DialogTitle>Редактирование позиции</DialogTitle>
          <DialogContent dividers>
            {(() => {
              const source = sourceSnapshot(editingPosition);

              return (
                <Stack spacing={3} sx={{ mt: 1 }}>
                  <Stack direction={{ xs: 'column', md: 'row' }} spacing={2}>
                    <TextField
                      label="Название позиции"
                      value={editingPosition.item_name}
                      onChange={(event) => updatePosition(editingPosition.id, { item_name: event.target.value })}
                      fullWidth
                    />
                    <TextField
                      select
                      label="Раздел"
                      value={editingPosition.room_id || COMMON_ROOM}
                      onChange={(event) => updatePosition(editingPosition.id, { room_id: event.target.value === COMMON_ROOM ? null : event.target.value })}
                      sx={{ minWidth: 200 }}
                    >
                      {estimateDraft.useCommonSection && <MenuItem value={COMMON_ROOM}>Общие работы</MenuItem>}
                      {roomDrafts.map((room) => <MenuItem key={room.id} value={room.id}>{room.name}</MenuItem>)}
                    </TextField>
                  </Stack>

                  <Stack direction={{ xs: 'column', md: 'row' }} spacing={2}>
                    <TextField
                      label="Кол-во"
                      type="number"
                      value={editingPosition.qty}
                      onChange={(event) => updatePosition(editingPosition.id, { qty: num(event.target.value) })}
                      sx={{ width: 130 }}
                    />
                    <TextField
                      label="Ед. изм."
                      value={editingPosition.unit || ''}
                      onChange={(event) => updatePosition(editingPosition.id, { unit: event.target.value })}
                      sx={{ width: 100 }}
                    />
                    <TextField
                      label="Цена за ед."
                      type="number"
                      value={editingPosition.price}
                      onChange={(event) => updatePosition(editingPosition.id, { price: num(event.target.value) })}
                      sx={{ width: 150 }}
                    />
                    <Box sx={{ p: 2, bgcolor: 'grey.50', borderRadius: 1, flexGrow: 1, textAlign: 'right' }}>
                      <Typography variant="body2" color="text.secondary">Сумма</Typography>
                      <Typography variant="h6" color="primary.main">{money(num(editingPosition.total))}</Typography>
                    </Box>
                  </Stack>

                  <Divider />

                  <Typography variant="subtitle2" color="text.secondary">Дополнительные данные</Typography>
                  <Stack direction={{ xs: 'column', md: 'row' }} spacing={2}>
                    <TextField
                      label="Категория"
                      value={editingPosition.category || ''}
                      onChange={(event) => updatePosition(editingPosition.id, { category: event.target.value })}
                      fullWidth
                    />
                    <TextField
                      label="Подкатегория"
                      value={editingPosition.subcategory || ''}
                      onChange={(event) => updatePosition(editingPosition.id, { subcategory: event.target.value })}
                      fullWidth
                    />
                  </Stack>
                  <Stack direction={{ xs: 'column', md: 'row' }} spacing={2}>
                    <TextField
                      label="Фото для КП (URL)"
                      value={textValue(source.image)}
                      onChange={(event) => updatePositionSource(editingPosition.id, { image: event.target.value })}
                      fullWidth
                    />
                    <TextField
                      label="Описание для КП"
                      value={textValue(source.description)}
                      onChange={(event) => updatePositionSource(editingPosition.id, { description: event.target.value })}
                      multiline
                      minRows={2}
                      fullWidth
                    />
                  </Stack>
                </Stack>
              );
            })()}
          </DialogContent>
          <DialogActions>
            <Button onClick={() => setEditingPositionId(null)} variant="contained" color="primary">Готово</Button>
          </DialogActions>
        </Dialog>
      )}
    </Box>
  );
}
